pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Deploy') {
      steps {
        sh '''
          chmod +x 04-phase4-final-project/scripts/deploy.sh
          04-phase4-final-project/scripts/deploy.sh
        '''
      }
    }

    stage('Verify') {
      steps {
        sh '''
          chmod +x 04-phase4-final-project/scripts/verify.sh
          04-phase4-final-project/scripts/verify.sh
        '''
      }
    }
  }
}
