pipeline {
  agent any

  options {
    timestamps()
    disableConcurrentBuilds()
    buildDiscarder(logRotator(numToKeepStr: '10'))
  }

  environment {
    COMPOSE_FILE = "devops-final-project/docker-compose.yml"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build') {
      steps {
        sh 'docker compose -f $COMPOSE_FILE build app'
      }
    }

    stage('Deploy') {
      steps {
        sh 'docker compose -f $COMPOSE_FILE up -d --remove-orphans app'
      }
    }

    stage('Smoke Test') {
      steps {
        sh 'sleep 3'
        sh 'curl -f http://localhost:3000/health'
      }
    }
  }

  post {
    always {
      sh 'docker system df || true'
    }
  }
}
